FROM dart:stable AS build

WORKDIR /app

COPY pubspec.* ./
RUN dart pub get

COPY . .

RUN dart compile exe servers/signals_server.dart -o signals_server

FROM debian:stable-slim

WORKDIR /app

COPY --from=build /app/signals_server .

EXPOSE 8080

CMD ["./signals_server"]