# ---------- Build Stage ----------
FROM dart:stable AS build

WORKDIR /app

# Copy pubspec first (cache-friendly)
COPY pubspec.* ./

RUN dart pub get

# Copy signals server source
COPY servers/signals_server.dart ./servers/signals_server.dart

# Compile signals server
RUN dart compile exe servers/signals_server.dart -o servers/signals_server_exec

# ---------- Runtime Stage ----------
FROM scratch AS runtime
WORKDIR /app

# Copy compiled executable
COPY --from=build /app/servers/signals_server_exec ./servers/signals_server_exec

# Expose signals server port
EXPOSE 8081

# Run signals server executable
CMD ["./servers/signals_server_exec"]